import Link from "next/link";
import { Zap } from "lucide-react";

export const metadata = { title: "Terms of Service" };

export default function TermsPage() {
  return (
    <div className="min-h-screen px-6 py-16">
      <div className="max-w-2xl mx-auto">
        <Link href="/" className="inline-flex items-center gap-2 mb-10">
          <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-cyan">
            <Zap className="h-3.5 w-3.5 text-void" />
          </div>
          <span className="font-medium text-text-primary">NexDesk</span>
        </Link>

        <h1 className="font-[family-name:var(--font-display)] text-3xl text-text-primary mb-2">Terms of Service</h1>
        <p className="text-sm text-text-muted mb-10">Last updated: July 2026</p>

        <div className="space-y-8 text-sm text-text-secondary leading-relaxed">
          <section>
            <h2 className="text-text-primary font-medium mb-2">Demo project</h2>
            <p>NexDesk is a demonstration project showcasing an AI-powered customer support platform for a fictional store, TechVault. It is not a live commercial service, and no real purchases, payments, or customer accounts are processed through it at this time.</p>
          </section>

          <section>
            <h2 className="text-text-primary font-medium mb-2">Use of the demo</h2>
            <p>You&apos;re welcome to try the live chat and dashboard to see how the platform works. Please don&apos;t submit real personal, financial, or sensitive information — this is a portfolio demonstration, not a production service handling real customer data at scale.</p>
          </section>

          <section>
            <h2 className="text-text-primary font-medium mb-2">AI-generated responses</h2>
            <p>Responses in the live chat are generated by AI agents and may occasionally be inaccurate or incomplete. Nothing said by the chat agents constitutes a real business commitment, offer, or contract.</p>
          </section>

          <section>
            <h2 className="text-text-primary font-medium mb-2">No warranty</h2>
            <p>This demo is provided as-is, without warranty of any kind, for demonstration and evaluation purposes.</p>
          </section>

          <section>
            <h2 className="text-text-primary font-medium mb-2">Contact</h2>
            <p>Questions: <a href="mailto:zainmalik.622aa@gmail.com" className="text-cyan hover:underline">zainmalik.622aa@gmail.com</a></p>
          </section>
        </div>
      </div>
    </div>
  );
}
